<a href="https://colab.research.google.com/github/AkashSinghal2599/firstlessonAK/blob/main/Arrray%20Transposition.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
array = np.arange(50).reshape((10,5))
array


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

here we learnt how create columns and rows in array using numpy


In [2]:
array.T

array([[ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46],
       [ 2,  7, 12, 17, 22, 27, 32, 37, 42, 47],
       [ 3,  8, 13, 18, 23, 28, 33, 38, 43, 48],
       [ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49]])

Here we learnt how to transposed or reverse the columns and rows in the array using numpy

In [4]:
np.dot(array.T, array)

array([[7125, 7350, 7575, 7800, 8025],
       [7350, 7585, 7820, 8055, 8290],
       [7575, 7820, 8065, 8310, 8555],
       [7800, 8055, 8310, 8565, 8820],
       [8025, 8290, 8555, 8820, 9085]])

In [5]:
np.dot(array, array.T)

array([[   30,    80,   130,   180,   230,   280,   330,   380,   430,
          480],
       [   80,   255,   430,   605,   780,   955,  1130,  1305,  1480,
         1655],
       [  130,   430,   730,  1030,  1330,  1630,  1930,  2230,  2530,
         2830],
       [  180,   605,  1030,  1455,  1880,  2305,  2730,  3155,  3580,
         4005],
       [  230,   780,  1330,  1880,  2430,  2980,  3530,  4080,  4630,
         5180],
       [  280,   955,  1630,  2305,  2980,  3655,  4330,  5005,  5680,
         6355],
       [  330,  1130,  1930,  2730,  3530,  4330,  5130,  5930,  6730,
         7530],
       [  380,  1305,  2230,  3155,  4080,  5005,  5930,  6855,  7780,
         8705],
       [  430,  1480,  2530,  3580,  4630,  5680,  6730,  7780,  8830,
         9880],
       [  480,  1655,  2830,  4005,  5180,  6355,  7530,  8705,  9880,
        11055]])

Here we learnt how to multiply two array or take out the dot product of two arrays horizontally and vertically both.

In [7]:
array3d = np.arange(50).reshape((5,5,2))
array3d

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]],

       [[30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39]],

       [[40, 41],
        [42, 43],
        [44, 45],
        [46, 47],
        [48, 49]]])

Here we learnt how to create 3D matrix. It's a 3D matrix with 5 slices and each slice consists of five by two array

In [8]:
array3d.transpose((1,0,2))

array([[[ 0,  1],
        [10, 11],
        [20, 21],
        [30, 31],
        [40, 41]],

       [[ 2,  3],
        [12, 13],
        [22, 23],
        [32, 33],
        [42, 43]],

       [[ 4,  5],
        [14, 15],
        [24, 25],
        [34, 35],
        [44, 45]],

       [[ 6,  7],
        [16, 17],
        [26, 27],
        [36, 37],
        [46, 47]],

       [[ 8,  9],
        [18, 19],
        [28, 29],
        [38, 39],
        [48, 49]]])

in the original 3d matrix we had 10,20,30 as the first row and first column as indexed value and now that's become the first column of the first slice and the same composition carries on. Basically here we learnt how to arrange a matrix in the way we want.

In [13]:
Akash = np.array([[1,2,3]])
Akash

array([[1, 2, 3]])

In [20]:
Akash.swapaxes(0,1)

array([[1],
       [2],
       [3]])

Here we learnt how to swap axes and made an array by swapping the zero axes into ones axes. Basically we made a vertical array out of an horizontal array.

This chapter was on array transpostion. It taught me how to create an array and change it from horizontal to vertical, taught me to make 3d array and how to slice it.