In [4]:
import numpy as np
my_lists1 = [1,2,3]
my_array1 = np.array(my_lists1)
my_array1

array([1, 2, 3])

In [9]:
my_lists2 = [11,22,33]
my_array2 = np.array(my_lists2)
my_array2

array([11, 22, 33])

In [10]:
my_lists = [my_lists1,my_lists2]
my_array = np.array(my_lists)
my_array

array([[ 1,  2,  3],
       [11, 22, 33]])

In [12]:
my_array.shape

(2, 3)

In [13]:
my_array.dtype

dtype('int64')

In [14]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [17]:
my_zeros_array = np.zeros(5)
my_zeros_array.dtype

dtype('float64')

In [19]:
np.ones([5,5])


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [20]:
np.empty(5)

array([0., 0., 0., 0., 0.])

In [21]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [22]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [23]:
np.arange(5,50,2)

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37,
       39, 41, 43, 45, 47, 49])