<a href="https://colab.research.google.com/github/AkashSinghal2599/firstlessonAK/blob/main/Indexing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
array = np.arange(0,11)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
array[8]

8

In [21]:
array[1:9]

array([100, 100, 100, 100,   5,   6,   7,   8])

In [23]:
array[3] = 5
array

array([100, 100, 100,   5, 100,   5,   6,   7,   8,   9,  10])

In [24]:
array = np.arange(0,11)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
Akash = np.arange(2,24)
Akash

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23])

In [28]:
slice_of_Akash = Akash[2:18]
slice_of_Akash

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [30]:
slice_of_Akash[:] = 99
slice_of_Akash

array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99])

In [31]:
Akash

array([ 2,  3, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99,
       99, 20, 21, 22, 23])

In [32]:
Akash_copy = Akash.copy()
Akash_copy

array([ 2,  3, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99,
       99, 20, 21, 22, 23])

In [33]:
Vertika = np.array(([1,2,3],[4,5,6],[7,8,9]))
Vertika

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
Vertika[2]

array([7, 8, 9])

In python Counting starts with 0 not with 1

In [36]:
Vertika[0][2]

3

In [37]:
Vertika

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
Vertika[:1,2:]

array([[3]])

In [41]:
Vertika[:2,1:]

array([[2, 3],
       [5, 6]])

In [43]:
Vertika[:1,0:]

array([[1, 2, 3]])

In [44]:
Vertika[1]

array([4, 5, 6])

In [65]:
Noor = np.zeros((10,10))
Noor

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

You can make array of any number by writing np.number(()) using this code


In [66]:
arr_length = Noor.shape[1]
arr_length

10

This is a 2d array that's why it couldn't print the when asked for 4th or another column,row

In [69]:
for i in range(arr_length):
  Noor[i]=i

If you need to change the value in array.

In [70]:
Noor

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

To select particular value in an array. It's called fancy Indexing.

In [71]:
Noor[[4,6,8,0]]

array([[4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])