<a href="https://colab.research.google.com/github/AkashSinghal2599/firstlessonAK/blob/main/second.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
5/2

2.5

In [6]:
from __future__ import division
5/2

2.5

In [9]:
array1 = np.array([[1,2,3],[4,5,6]])
array1

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
array1*array1

array([[ 1,  4,  9],
       [16, 25, 36]])

In [11]:
array1 - array1

array([[0, 0, 0],
       [0, 0, 0]])

In [12]:
1 / array1

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [15]:
array1 ** 3

array([[  1,   8,  27],
       [ 64, 125, 216]])