<a href="https://colab.research.google.com/github/AkashSinghal2599/firstlessonAK/blob/main/Universal_Array_Function_Lecture11.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
array = np.arange(11)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [2]:
np.sqrt(array)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [3]:
np.exp(array)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

Here we learnt how to use universal functions of an Array like square root and exponential

and now we move forward to binary functions

for doing that we will create a random array which we will do by using random array from numpy and then we will make a random distribution

In [5]:
A = np.random.randn(10)
A

array([-0.18477349, -0.88139486,  1.6500646 ,  0.29682327,  0.35388725,
        0.18523971,  0.62450546,  0.20344995,  1.94894107,  0.18365801])

In [6]:
B = np.random.randn(10)
B

array([-0.7040525 ,  0.34155143, -0.53674168, -0.66596785, -0.55854616,
       -0.45354561, -0.05739228,  1.42796623, -0.96504493,  0.44344373])

Here we learnt how to do random distribution of numbers using random library on numpy and now we have two arrays with normal distribution with some random numbers.  Now we are moving on to learn binary functions.

In [7]:
np.add(A,B)

array([-0.88882599, -0.53984343,  1.11332293, -0.36914458, -0.20465891,
       -0.26830591,  0.56711317,  1.63141618,  0.98389614,  0.62710174])

how to add arrays and now we are going to learn how to find maximum or minimum in an array.

In [8]:
np.maximum(A,B)

array([-0.18477349,  0.34155143,  1.6500646 ,  0.29682327,  0.35388725,
        0.18523971,  0.62450546,  1.42796623,  1.94894107,  0.44344373])

In [9]:
np.minimum(A,B)

array([-0.7040525 , -0.88139486, -0.53674168, -0.66596785, -0.55854616,
       -0.45354561, -0.05739228,  0.20344995, -0.96504493,  0.18365801])

Now we will learn how to open a website by pasting the link in a browser.

In [16]:
website = 'http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs'
import webbrowser
webbrowser.open(website)

False